name: Schema update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1"

permissions:
  attestations: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: NPM install
        run: npm ci

      - name: Update schemas
        run: npm update @propulsionworks/cfn-resource-schemas

      - id: commit
        name: Commit changes
        continue-on-error: true
        run: |
          git add -A && git commit -m 'Chore: update resource schemas'

      - name: Generate resource types
        if: ${{ steps.commit.outcome == 'success' }}
        run: npm generate

      - name: Build
        if: ${{ steps.commit.outcome == 'success' }}
        run: npm run build

      - name: Release
        if: ${{ steps.commit.outcome == 'success' }}
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
